# Generated by Django 5.2.6 on 2025-11-05 15:47

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0021_alter_order_options_remove_order_deposit_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reminder_one', models.DateField(blank=True, null=True)),
                ('reminder_two', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_paid_off', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('shipping_courier', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='order.order')),
            ],
            options={
                'permissions': [('can_add_deposit', 'Can add deposit'), ('can_view_deposit', 'Can view deposit'), ('can_change_deposit', 'Can change deposit'), ('can_delete_deposit', 'Can delete deposit')],
                'default_permissions': (),
            },
        ),
    ]
