# Generated by Django 5.2.6 on 2025-11-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='priority_status',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('urgent', 'Urgent')], default='reguler', max_length=20),
        ),
    ]
