# Generated by Django 5.2.6 on 2025-11-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_deposit_priority_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='priority_status',
        ),
    ]
