# Generated by Django 5.2.6 on 2025-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_deposit_priority_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='lead_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
