# Generated by Django 5.2.6 on 2025-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_deposit_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
