# Generated by Django 5.2.6 on 2025-11-17 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_deposit_accepted_at'),
        ('order', '0032_alter_orderform_design_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='order.order'),
        ),
    ]
