# Generated by Django 5.2.6 on 2025-12-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_alter_deposit_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='priority_status',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('urgent', 'Urgent'), ('express', 'Express')], default='reguler', max_length=20),
        ),
    ]
