# Generated by Django 5.2.6 on 2026-06-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0008_alter_deposit_priority_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='paid_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
