# Generated by Django 5.2.6 on 2026-07-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0009_deposit_paid_off_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
