# Generated by Django 5.2.6 on 2025-11-22 02:53

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('sewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SewerDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('quantity', models.PositiveIntegerField(help_text='Jumlah yang dibagikan ke penjahit')),
                ('has_rib', models.BooleanField(default=False, verbose_name='Acc RIP')),
                ('has_collar', models.BooleanField(default=False, verbose_name='Acc Kerah')),
                ('has_sleeve', models.BooleanField(default=False, verbose_name='Acc Lengan')),
                ('has_pocket', models.BooleanField(default=False, verbose_name='Acc Saku')),
                ('notes', models.TextField(blank=True, null=True)),
                ('tracking_code', models.CharField(editable=False, help_text='Nomor Barcode unik untuk tracking', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributed_by', models.ForeignKey(help_text='QC Potong yang melakukan pembagian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions_created', to=settings.AUTH_USER_MODEL)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewer_distributions', to='forecast.forecast')),
                ('sewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sewing_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Nama Penjahit')),
            ],
            options={
                'verbose_name': 'sewer',
                'verbose_name_plural': 'sewers',
                'permissions': [('add_sewer_distribution', 'Can add sewer distribution'), ('view_sewer_distribution', 'Can view sewer distribution'), ('change_sewer_distribution', 'Can change sewer distribution'), ('delete_sewer_distribution', 'Can delete sewer distribution')],
                'default_permissions': (),
            },
        ),
    ]
