# Generated by Django 5.2.6 on 2025-11-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewer', '0002_sewerdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewerdistribution',
            name='sewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sewing_jobs', to='sewer.sewer', verbose_name='Nama Penjahit'),
        ),
    ]
