# Generated by Django 5.2.6 on 2025-12-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewer', '0003_alter_sewerdistribution_sewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewerdistribution',
            name='has_collar',
        ),
        migrations.RemoveField(
            model_name='sewerdistribution',
            name='has_pocket',
        ),
        migrations.RemoveField(
            model_name='sewerdistribution',
            name='has_rib',
        ),
        migrations.RemoveField(
            model_name='sewerdistribution',
            name='has_sleeve',
        ),
        migrations.AddField(
            model_name='sewerdistribution',
            name='accessories',
            field=models.JSONField(default=[]),
        ),
    ]
