# Generated by Django 5.2.6 on 2025-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewer', '0004_remove_sewerdistribution_has_collar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewerdistribution',
            name='is_full',
            field=models.BooleanField(default=True, verbose_name='Apakah Lengkap'),
        ),
    ]
