# Generated by Django 5.2.6 on 2026-01-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewer', '0005_sewerdistribution_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewerdistribution',
            name='type',
            field=models.CharField(choices=[('OBRAS', 'Obras'), ('JAHIT', 'Jahit'), ('OVERDECK', 'Overdeck')], default='JAHIT', max_length=20),
        ),
    ]
