# Generated by Django 5.2.6 on 2026-01-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewer', '0006_sewerdistribution_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewerdistribution',
            name='type',
        ),
        migrations.AddField(
            model_name='sewerdistribution',
            name='distribution_type',
            field=models.CharField(choices=[('obras', 'Obras'), ('jahit', 'Jahit'), ('overdeck', 'Overdeck')], default='jahit', max_length=20),
            preserve_default=False,
        ),
    ]
