# Generated by Django 5.2.6 on 2025-12-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='is_stock',
            field=models.BooleanField(default=False),
        ),
    ]
