# Generated by Django 5.2.6 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_forecast_is_stock'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='printer.printer'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
