# Generated by Django 5.2.6 on 2025-12-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_forecast_printer_forecast_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='priority_status',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('urgent', 'Urgent'), ('express', 'Express')], default='reguler', max_length=20),
        ),
    ]
