# Generated by Django 5.2.6 on 2025-12-10 05:23

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_forecast_priority_status'),
        ('product', '0014_productvarianttype_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='product.fabrictype')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='forecast.forecast')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='product.product')),
                ('variant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='product.productvarianttype')),
            ],
            options={
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
