# Generated by Django 5.2.6 on 2025-12-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='price',
        ),
    ]
