# Generated by Django 5.2.6 on 2025-12-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_remove_stockitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='estimate_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='priority_status',
            field=models.CharField(blank=True, choices=[('reguler', 'Reguler'), ('urgent', 'Urgent'), ('express', 'Express')], max_length=20, null=True),
        ),
    ]
