# Generated by Django 5.2.6 on 2025-12-10 06:45

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_forecast_estimate_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('size', models.CharField(max_length=100)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item_sizes', to='forecast.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Item Size',
                'verbose_name_plural': 'Stock Item Sizes',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
