# Generated by Django 5.2.6 on 2025-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_stockitemsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitemsize',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
