# Generated by Django 5.2.6 on 2025-12-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_stockitemsize_qty'),
        ('order', '0038_alter_order_order_type_alter_order_priority_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='order.orderitem'),
        ),
    ]
