# Generated by Django 5.2.6 on 2026-01-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_alter_forecast_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='forecast_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
