# Generated by Django 5.2.6 on 2026-01-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0011_forecast_forecast_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
