# Generated by Django 5.2.6 on 2026-07-19 00:48

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('object_id', models.PositiveBigIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('defect', models.CharField(max_length=255)),
                ('hpp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reject',
                'verbose_name_plural': 'Rejects',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
