# Generated by Django 5.2.6 on 2026-07-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reject',
            options={'default_permissions': (), 'permissions': [('can_add_defect', 'Can add defect'), ('can_view_defect', 'Can view defect'), ('can_change_defect', 'Can change defect'), ('can_delete_defect', 'Can delete defect')], 'verbose_name': 'Reject', 'verbose_name_plural': 'Rejects'},
        ),
    ]
