# Generated by Django 5.2.6 on 2026-07-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0002_alter_reject_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reject',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='reject',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
