# Generated by Django 5.2.6 on 2026-07-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0004_reject_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reject',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
    ]
