# Generated by Django 5.2.6 on 2026-07-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0005_alter_reject_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reject',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
