# Generated by Django 5.2.6 on 2025-11-21 12:53

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Apakah hasil pengecekan sudah sesuai?')),
                ('rejected_quantity', models.PositiveIntegerField(default=0, help_text='Jumlah hasil yang tidak sesuai (pcs)')),
                ('rejection_note', models.TextField(blank=True, help_text='Keterangan bagian yang tidak sesuai', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Waktu print selesai dikerjakan', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='forecast.forecast')),
                ('verified_by', models.ForeignKey(help_text='Personil Print yang melakukan pengecekan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Verification',
                'verbose_name_plural': 'Print Verifications',
                'permissions': [('add_print_verification', 'Can add print verification'), ('view_print_verification', 'Can view print verification'), ('change_print_verification', 'Can change print verification'), ('delete_print_verification', 'Can delete print verification')],
                'default_permissions': (),
            },
        ),
    ]
