# Generated by Django 5.2.6 on 2025-11-21 12:57

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCLineVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Hasil Pengecekan Sesuai?')),
                ('rejected_quantity', models.PositiveIntegerField(default=0, help_text='Jumlah hasil yang tidak sesuai (pcs)')),
                ('defect_area', models.CharField(blank=True, choices=[('atasan', 'Atasan'), ('lengan_kanan', 'Lengan Kanan'), ('lengan_kiri', 'Lengan Kiri'), ('bagian_depan', 'Bagian Depan'), ('bagian_belakang', 'Bagian Belakang'), ('kerah', 'Kerah'), ('celana_kiri', 'Celana Kiri'), ('celana_kanan', 'Celana Kanan'), ('satu_stel', 'Satu Stel (Atasan dan Celana)'), ('lainnya', 'Keterangan Lainnya')], help_text='Pilih bagian yang rusak jika tidak sesuai', max_length=50, null=True)),
                ('defect_note', models.TextField(blank=True, help_text="Detail kerusakan jika memilih 'Keterangan Lainnya' atau info tambahan", null=True, verbose_name='Keterangan Lainnya')),
                ('defect_image', models.ImageField(blank=True, help_text='Upload foto bukti reject', null=True, upload_to='qc_defects/%Y/%m/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(help_text='QC yang melakukan proses pengecekan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_line_verification', to='forecast.forecast')),
            ],
            options={
                'verbose_name': 'QC Line Verification',
                'verbose_name_plural': 'QC Line Verifications',
                'permissions': [('add_qc_line_verification', 'Can add QC line verification'), ('view_qc_line_verification', 'Can view QC line verification'), ('change_qc_line_verification', 'Can change QC line verification'), ('delete_qc_line_verification', 'Can delete QC line verification')],
                'default_permissions': (),
            },
        ),
    ]
