# Generated by Django 5.2.6 on 2025-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_qclineverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qclineverification',
            name='defect_image',
            field=models.ImageField(blank=True, help_text='Upload foto bukti reject', null=True, upload_to='qc_defects/'),
        ),
    ]
