# Generated by Django 5.2.6 on 2025-12-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_alter_qccuttingverification_defect_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qccuttingverification',
            name='defect_area',
            field=models.JSONField(help_text='Pilih bagian yang rusak jika tidak sesuai'),
        ),
        migrations.AlterField(
            model_name='qclineverification',
            name='defect_area',
            field=models.JSONField(help_text='Pilih bagian yang rusak jika tidak sesuai'),
        ),
    ]
