# Generated by Django 5.2.6 on 2025-12-13 23:31

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_stockitemsize_qty'),
        ('verification', '0006_alter_qccuttingverification_defect_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('received_quantity', models.PositiveIntegerField()),
                ('realization_status', models.CharField(choices=[('ok', 'OK (Lengkap)'), ('kurang', 'Kurang')], max_length=10)),
                ('verification_code', models.CharField(editable=False, help_text='Nomor untuk verifikasi Admin Gudang', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_finishing', to='forecast.forecast')),
                ('verified_by', models.ForeignKey(help_text='Personil QC Finishing yang melakukan pengecekan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QC Finishing Verification',
                'verbose_name_plural': 'QC Finishing Verifications',
                'permissions': [('add_qc_finishing', 'Can add qc finishing verification'), ('view_qc_finishing', 'Can view qc finishing verification'), ('change_qc_finishing', 'Can change qc finishing verification'), ('delete_qc_finishing', 'Can delete qc finishing verification')],
                'default_permissions': (),
            },
        ),
    ]
