# Generated by Django 5.2.6 on 2025-12-13 23:47

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_stockitemsize_qty'),
        ('verification', '0007_qcfinishing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCFinishingDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('quantity_rejected', models.PositiveIntegerField(verbose_name='Jumlah Reject/Kembali')),
                ('reason', models.TextField(blank=True, help_text='Alasan dikembalikan', null=True)),
                ('is_repaired', models.BooleanField(default=False, help_text='Centang jika penjahit sudah memperbaiki dan mengembalikan lagi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(help_text='QC Finishing yang menemukan defect', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_finishing_defect', to='forecast.forecast')),
            ],
            options={
                'verbose_name': 'QC Finishing Defect Verification',
                'verbose_name_plural': 'QC Finishing Defect Verifications',
                'permissions': [('add_qc_finishing_defect', 'Can add qc finishing defect verification'), ('view_qc_finishing_defect', 'Can view qc finishing defect verification'), ('change_qc_finishing_defect', 'Can change qc finishing defect verification'), ('delete_qc_finishing_defect', 'Can delete qc finishing defect verification')],
                'default_permissions': (),
            },
        ),
    ]
