# Generated by Django 5.2.6 on 2025-12-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_alter_forecast_order_item'),
        ('verification', '0008_qcfinishingdefect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printverification',
            name='forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_verifications', to='forecast.forecast'),
        ),
        migrations.AlterField(
            model_name='qccuttingverification',
            name='forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_cutting_verifications', to='forecast.forecast'),
        ),
        migrations.AlterField(
            model_name='qcfinishing',
            name='forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_finishings', to='forecast.forecast'),
        ),
        migrations.AlterField(
            model_name='qcfinishingdefect',
            name='forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_finishing_defects', to='forecast.forecast'),
        ),
        migrations.AlterField(
            model_name='qclineverification',
            name='forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_line_verifications', to='forecast.forecast'),
        ),
    ]
