# Generated by Django 5.2.6 on 2026-02-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_alter_printverification_forecast_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printverification',
            options={'default_permissions': (), 'permissions': [('view_print', 'Can view print verification'), ('verify_print', 'Can verify print verification')], 'verbose_name': 'Print Verification', 'verbose_name_plural': 'Print Verifications'},
        ),
        migrations.AlterModelOptions(
            name='qccuttingverification',
            options={'default_permissions': (), 'permissions': [('view_qc_cutting', 'Can view qc cutting verification'), ('verify_qc_cutting', 'Can verify qc cutting verification'), ('sewer_distribution', 'Can sewer distribution')], 'verbose_name': 'QC Cutting Verification', 'verbose_name_plural': 'QC Cutting Verifications'},
        ),
        migrations.AlterModelOptions(
            name='qcfinishing',
            options={'default_permissions': (), 'permissions': [('view_finishing', 'Can view finishing verification'), ('verify_finishing', 'Can verify finishing verification')], 'verbose_name': 'QC Finishing Verification', 'verbose_name_plural': 'QC Finishing Verifications'},
        ),
        migrations.AlterModelOptions(
            name='qcfinishingdefect',
            options={'default_permissions': (), 'permissions': [('verify_defect_finishing', 'Can verify defect finishing verification')], 'verbose_name': 'QC Finishing Defect Verification', 'verbose_name_plural': 'QC Finishing Defect Verifications'},
        ),
        migrations.AlterModelOptions(
            name='qclineverification',
            options={'default_permissions': (), 'permissions': [('view_line', 'Can view line verification'), ('verify_line', 'Can verify line verification')], 'verbose_name': 'QC Line Verification', 'verbose_name_plural': 'QC Line Verifications'},
        ),
    ]
