# Generated by Django 5.2.6 on 2026-02-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0010_alter_printverification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qccuttingverification',
            options={'default_permissions': (), 'permissions': [('view_cutting', 'Can view qc cutting verification'), ('verify_cutting', 'Can verify qc cutting verification'), ('sewer_distribution', 'Can sewer distribution')], 'verbose_name': 'QC Cutting Verification', 'verbose_name_plural': 'QC Cutting Verifications'},
        ),
    ]
