# Generated by Django 5.2.6 on 2026-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0011_alter_qccuttingverification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='printverification',
            name='error_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
