# Generated by Django 5.2.6 on 2026-07-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0013_qclineverification_error_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccuttingverification',
            name='error_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
