# Generated by Django 5.2.6 on 2026-07-18 02:17

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0012_alter_forecast_forecast_number'),
        ('verification', '0016_qcfinishing_error_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCPressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Hasil Pengecekan Sesuai?')),
                ('rejected_quantity', models.PositiveIntegerField(default=0, help_text='Jumlah hasil yang tidak sesuai (pcs)')),
                ('defect_area', models.JSONField(help_text='Pilih bagian yang rusak jika tidak sesuai')),
                ('defect_note', models.TextField(blank=True, help_text="Detail kerusakan jika memilih 'Keterangan Lainnya' atau info tambahan", null=True, verbose_name='Keterangan Lainnya')),
                ('defect_image', models.ImageField(blank=True, help_text='Upload foto bukti reject', null=True, upload_to='qc_defects/')),
                ('error_from', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(help_text='QC yang melakukan proses pengecekan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_press_verifications', to='forecast.forecast')),
            ],
            options={
                'verbose_name': 'QC Press Verification',
                'verbose_name_plural': 'QC Press Verifications',
                'permissions': [('view_press', 'Can view press verification'), ('verify_press', 'Can verify press verification')],
                'default_permissions': (),
            },
        ),
    ]
