# Generated by Django 5.2.6 on 2025-10-15 12:28

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_created_at_order_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtraCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('ongkir', 'Biaya Ongkos Kirim'), ('charge', 'Biaya Tambahan'), ('discount', 'Diskon'), ('promo', 'Promo')], default='charge', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
