# Generated by Django 5.2.6 on 2025-10-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderextracost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderextracost',
            name='total_amount',
        ),
    ]
