# Generated by Django 5.2.6 on 2025-10-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderextracost_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_extra_cost',
        ),
    ]
