# Generated by Django 5.2.6 on 2025-10-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_invoice_total_extra_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_invoice',
        ),
    ]
