# Generated by Django 5.2.6 on 2025-10-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_invoice_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
