# Generated by Django 5.2.6 on 2025-10-16 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_identity'),
        ('order', '0007_remove_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketplace',
            field=models.CharField(blank=True, choices=[('shopee', 'Shopee'), ('tiktok', 'TikTok'), ('tokopedia', 'Tokopedia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_choice',
            field=models.CharField(blank=True, choices=[('custom_design', 'Custom Design'), ('top', 'Top'), ('pants', 'Pants'), ('set', 'Set')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
