# Generated by Django 5.2.6 on 2025-10-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_estimated_shipping_date_order_marketplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_courier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
