# Generated by Django 5.2.6 on 2025-10-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_is_expired_order_note_order_reminder_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
