# Generated by Django 5.2.6 on 2025-10-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_product_name_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid_off',
            field=models.BooleanField(default=False),
        ),
    ]
