# Generated by Django 5.2.6 on 2025-10-16 12:20

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_is_paid_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('design_front', models.CharField(blank=True, max_length=255, null=True)),
                ('design_back', models.CharField(blank=True, max_length=255, null=True)),
                ('jersey_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('jersey_type', models.CharField(blank=True, max_length=255, null=True)),
                ('jersey_cutting', models.CharField(blank=True, max_length=255, null=True)),
                ('collar_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pants_cutting', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_logo_ez', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_size_bottom', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_size_shoulder', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_chest_right', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_center', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_chest_left', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_back', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_pants', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Form',
                'verbose_name_plural': 'Order Forms',
            },
        ),
    ]
