# Generated by Django 5.2.6 on 2025-10-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='convection_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
