# Generated by Django 5.2.6 on 2025-10-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_convection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reminder_one',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reminder_two',
        ),
    ]
