# Generated by Django 5.2.6 on 2025-10-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_convection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reminder_one',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reminder_two',
            field=models.DateField(blank=True, null=True),
        ),
    ]
