# Generated by Django 5.2.6 on 2025-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_order_reminder_one_remove_order_reminder_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder_one',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_two',
            field=models.DateField(blank=True, null=True),
        ),
    ]
