# Generated by Django 5.2.6 on 2025-10-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_reminder_one_order_reminder_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_add_order_marketplace', 'Can add marketplace order'), ('can_view_order_marketplace', 'Can view marketplace order'), ('can_change_order_marketplace', 'Can change marketplace order'), ('can_delete_order_marketplace', 'Can delete marketplace order'), ('can_add_deposit', 'Can add deposit'), ('can_view_deposit', 'Can view deposit'), ('can_change_deposit', 'Can change deposit'), ('can_delete_deposit', 'Can delete deposit')]},
        ),
        migrations.AlterModelOptions(
            name='orderextracost',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Extra Cost', 'verbose_name_plural': 'Extra Costs'},
        ),
        migrations.AlterModelOptions(
            name='orderform',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Order Form', 'verbose_name_plural': 'Order Forms'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'default_permissions': (), 'permissions': ()},
        ),
    ]
