# Generated by Django 5.2.6 on 2025-10-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_invoice_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': (), 'permissions': [('can_add_order_marketplace', 'Can add marketplace order'), ('can_view_order_marketplace', 'Can view marketplace order'), ('can_change_order_marketplace', 'Can change marketplace order'), ('can_delete_order_marketplace', 'Can delete marketplace order'), ('can_add_deposit', 'Can add deposit'), ('can_view_deposit', 'Can view deposit'), ('can_change_deposit', 'Can change deposit'), ('can_delete_deposit', 'Can delete deposit')]},
        ),
    ]
