# Generated by Django 5.2.6 on 2025-10-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderform',
            options={'default_permissions': (), 'permissions': [('view_orderform', 'Can view order form'), ('add_orderform', 'Can add order form'), ('change_orderform', 'Can change order form'), ('delete_orderform', 'Can delete order form')], 'verbose_name': 'Order Form', 'verbose_name_plural': 'Order Forms'},
        ),
    ]
