# Generated by Django 5.2.6 on 2025-10-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_orderform_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderform',
            name='order',
        ),
        migrations.AddField(
            model_name='orderform',
            name='order_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='order.orderitem'),
            preserve_default=False,
        ),
    ]
