# Generated by Django 5.2.6 on 2025-10-31 12:10

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_orderform_order_orderform_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('back_name', models.CharField(max_length=100)),
                ('jersey_number', models.CharField(max_length=100)),
                ('shirt_size', models.CharField(max_length=100)),
                ('pants_size', models.CharField(max_length=100)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_details', to='order.orderform')),
            ],
            options={
                'verbose_name': 'Order Form Detail',
                'verbose_name_plural': 'Order Form Details',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
