# Generated by Django 5.2.6 on 2025-11-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_orderformdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': (), 'permissions': [('can_add_order_marketplace', 'Can add marketplace order'), ('can_view_order_marketplace', 'Can view marketplace order'), ('can_change_order_marketplace', 'Can change marketplace order'), ('can_delete_order_marketplace', 'Can delete marketplace order')]},
        ),
        migrations.RemoveField(
            model_name='order',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid_off',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reminder_one',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reminder_two',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_courier',
        ),
    ]
