# Generated by Django 5.2.6 on 2025-11-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
        ('order', '0021_alter_order_options_remove_order_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='deposit.deposit'),
        ),
        migrations.AddField(
            model_name='orderextracost',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='deposit.deposit'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deposit.deposit'),
        ),
    ]
