# Generated by Django 5.2.6 on 2025-11-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_deposit_priority_status'),
        ('order', '0023_alter_invoice_order_alter_orderextracost_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextracost',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='deposit.deposit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deposit.deposit'),
        ),
    ]
