# Generated by Django 5.2.6 on 2025-11-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='note',
        ),
    ]
