# Generated by Django 5.2.6 on 2025-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='logo_back',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='logo_center',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='logo_chest_left',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='logo_chest_right',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='logo_pants',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='logos/'),
        ),
    ]
