# Generated by Django 5.2.6 on 2025-11-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_orderform_logo_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='form_type',
            field=models.CharField(choices=[('konveksi', 'Konveksi'), ('marketplace', 'Marketplace')], default='konveksi', max_length=20),
            preserve_default=False,
        ),
    ]
