# Generated by Django 5.2.6 on 2025-11-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_orderform_created_orderform_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderformdetail',
            old_name='order_item',
            new_name='order_form',
        ),
    ]
