# Generated by Django 5.2.6 on 2025-11-16 05:47

import services.order.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_rename_order_item_orderformdetail_order_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.CharField(blank=True, default=services.order.models.order.generate_order_id, max_length=20, null=True),
        ),
    ]
