# Generated by Django 5.2.6 on 2025-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_order_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='design_back',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='design_front',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='designs/'),
        ),
    ]
