# Generated by Django 5.2.6 on 2025-11-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_orderform_design_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='order.orderitem'),
        ),
    ]
