# Generated by Django 5.2.6 on 2025-11-19 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_orderform_order_item'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='email_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderform',
            name='marketplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderform',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='printer.printer'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
