# Generated by Django 5.2.6 on 2025-11-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_orderform_email_send_date_orderform_marketplace_and_more'),
        ('product', '0014_productvarianttype_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='product.fabrictype'),
        ),
    ]
