# Generated by Django 5.2.6 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_orderform_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='preview_print_back',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='preview_prints/'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='preview_print_front',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='preview_prints/'),
        ),
    ]
