# Generated by Django 5.2.6 on 2025-12-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_orderform_preview_print_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('konveksi', 'Konveksi'), ('marketplace', 'Marketplace'), ('express', 'Express')], max_length=20),
        ),
    ]
