# Generated by Django 5.2.6 on 2025-12-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('konveksi', 'Konveksi'), ('marketplace', 'Marketplace')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority_status',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('urgent', 'Urgent'), ('express', 'Express')], default='reguler', max_length=20),
        ),
    ]
