# Generated by Django 5.2.6 on 2026-07-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_deposit_pic'),
        ('order', '0038_alter_order_order_type_alter_order_priority_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='deposit.deposit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='order.order'),
        ),
    ]
