# Generated by Django 5.2.6 on 2026-07-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_deposit_pic'),
        ('order', '0039_alter_invoice_deposit_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='deposit.deposit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='order.order'),
        ),
    ]
