# Generated by Django 5.2.6 on 2026-07-02 00:32

import services.order.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_invoice_deposit_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.CharField(blank=True, default=services.order.models.order.generate_order_id, max_length=200, null=True),
        ),
    ]
