# Generated by Django 5.2.6 on 2025-12-15 14:53

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0010_alter_forecast_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Penerimaan')),
                ('receive_detail', models.JSONField()),
                ('defect_detail', models.JSONField()),
                ('note', models.TextField(blank=True, help_text='Keterangan jika jumlah berbeda dengan forecast', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipts', to='forecast.forecast')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin Gudang')),
            ],
            options={
                'verbose_name': 'Warehouse Receipt',
                'verbose_name_plural': 'Warehouse Receipts',
                'permissions': [('add_warehouse_receipt', 'Can add warehouse receipt'), ('view_warehouse_receipt', 'Can view warehouse receipt'), ('change_warehouse_receipt', 'Can change warehouse receipt'), ('delete_warehouse_receipt', 'Can delete warehouse receipt')],
                'default_permissions': (),
            },
        ),
    ]
