# Generated by Django 5.2.6 on 2025-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='defect_note',
            field=models.TextField(blank=True, help_text='Catatan jika ada defect di gudang', null=True),
        ),
    ]
