# Generated by Django 5.2.6 on 2025-12-29 09:35

import core.common.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousereceipt_defect_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('KAIN', 'Kain'), ('KERTAS', 'Kertas'), ('TINTA', 'Tinta'), ('PLASTIK', 'Plastik')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Specific details (e.g., jenis kain)')),
                ('unit', models.CharField(choices=[('PCS', 'Pcs'), ('KOLI', 'Koli'), ('ROLL', 'Roll'), ('DUS', 'Dus')], max_length=10)),
                ('current_stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'permissions': [('add_material', 'Can add material'), ('view_material', 'Can view material'), ('change_material', 'Can change material'), ('delete_material', 'Can delete material')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'permissions': [('add_supplier', 'Can add supplier'), ('view_supplier', 'Can view supplier'), ('change_supplier', 'Can change supplier'), ('delete_supplier', 'Can delete supplier')],
                'default_permissions': (),
            },
        ),
    ]
