# Generated by Django 5.2.6 on 2025-12-29 09:40

import core.common.generators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_material_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('qty_ordered', models.IntegerField()),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'permissions': [('add_purchase_order', 'Can add purchase order'), ('view_purchase_order', 'Can view purchase order'), ('change_purchase_order', 'Can change purchase order'), ('delete_purchase_order', 'Can delete purchase order')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StockOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('date_so', models.DateField(default=django.utils.timezone.now)),
                ('qty_system', models.IntegerField(help_text='Stock in system at moment of SO')),
                ('qty_actual', models.IntegerField(help_text='Physical count')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material')),
            ],
            options={
                'verbose_name': 'Stock Opname',
                'verbose_name_plural': 'Stock Opnames',
                'permissions': [('add_stock_opname', 'Can add stock opname'), ('view_stock_opname', 'Can view stock opname'), ('change_stock_opname', 'Can change stock opname'), ('delete_stock_opname', 'Can delete stock opname')],
                'default_permissions': (),
            },
        ),
    ]
