# Generated by Django 5.2.6 on 2026-01-06 01:49

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_alter_forecast_order_item'),
        ('warehouse', '0005_issuing_receiving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('delivery_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Pengiriman')),
                ('delivery_detail', models.JSONField()),
                ('defect_count', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, help_text='Keterangan / alasan barang yang dikirim defect', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin Gudang')),
                ('forecast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_deliveries', to='forecast.forecast')),
            ],
            options={
                'verbose_name': 'Warehouse Delivery',
                'verbose_name_plural': 'Warehouse Delivery',
                'permissions': [('add_warehouse_delivery', 'Can add warehouse delivery'), ('view_warehouse_delivery', 'Can view warehouse delivery'), ('change_warehouse_delivery', 'Can change warehouse delivery'), ('delete_warehouse_delivery', 'Can delete warehouse delivery')],
                'default_permissions': (),
            },
        ),
    ]
