# Generated by Django 5.2.6 on 2026-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_warehousedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousereceipt',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Penerimaan'),
        ),
    ]
