# Generated by Django 5.2.6 on 2026-02-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_warehousereceipt_received_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'default_permissions': (), 'permissions': [('add_material', 'Can add material'), ('view_material', 'Can view material'), ('change_material', 'Can change material'), ('delete_material', 'Can delete material'), ('stock_opname_material', 'Can stock opname material')], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'default_permissions': (), 'permissions': [('add_purchase_order', 'Can add purchase order'), ('view_purchase_order', 'Can view purchase order'), ('change_purchase_order', 'Can change purchase order'), ('delete_purchase_order', 'Can delete purchase order'), ('inbound_material', 'Can inbound material')], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='warehousedelivery',
            options={'default_permissions': (), 'permissions': [('view_warehouse_delivery', 'Can view warehouse delivery'), ('deliver_warehouse_delivery', 'Can deliver warehouse delivery')], 'verbose_name': 'Warehouse Delivery', 'verbose_name_plural': 'Warehouse Delivery'},
        ),
        migrations.AlterModelOptions(
            name='warehousereceipt',
            options={'default_permissions': (), 'permissions': [('view_warehouse_receipt', 'Can view warehouse receipt'), ('verify_warehouse_receipt', 'Can verify warehouse receipt')], 'verbose_name': 'Warehouse Receipt', 'verbose_name_plural': 'Warehouse Receipts'},
        ),
    ]
