# Generated by Django 5.2.6 on 2026-02-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_material_options_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'default_permissions': (), 'permissions': [('add_material', 'Can add material'), ('view_material', 'Can view material'), ('change_material', 'Can change material'), ('delete_material', 'Can delete material'), ('outbound_material', 'Can outbound material'), ('stock_opname_material', 'Can stock opname material')], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
    ]
