# Generated by Django 5.2.6 on 2026-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_material_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedelivery',
            name='production_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
