# Generated by Django 5.2.6 on 2025-12-29 02:23

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0038_alter_order_order_type_alter_order_priority_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('customer_name', models.CharField(max_length=255)),
                ('received_date', models.DateField()),
                ('complaint_type', models.CharField(choices=[('SIZE', 'Salah Ukuran'), ('DEFECT', 'Cacat'), ('COLOR', 'Warna Tidak Sesuai'), ('DESIGN', 'Salah Design')], max_length=20)),
                ('customer_request', models.CharField(choices=[('REPLACE', 'Ganti Barang'), ('REPAIR', 'Perbaikan'), ('REFUND', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('WAITING_QC', 'Menunggu QC'), ('QC_ACCEPTED', 'Diterima QC'), ('QC_REJECTED', 'Ditolak QC'), ('WAITING_APPROVAL', 'Menunggu Approval'), ('APPROVED', 'Disetujui'), ('IN_PROGRESS', 'Diproses Produksi'), ('CLOSED', 'Closed')], default='WAITING_QC', max_length=30)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
            options={
                'verbose_name': 'ticket complaint',
                'verbose_name_plural': 'ticket complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('action_type', models.CharField(choices=[('QC_VERIFY', 'QC Verification'), ('APPROVAL', 'Approval')], max_length=20)),
                ('result', models.CharField(choices=[('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak'), ('REPLACE', 'Kirim Ulang'), ('REPAIR', 'Perbaikan'), ('REFUND', 'Refund')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('estimated_finish_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ticket.complaintticket')),
            ],
            options={
                'verbose_name': 'ticket complaint action',
                'verbose_name_plural': 'ticket complaint actions',
            },
        ),
    ]
