# Generated by Django 5.2.6 on 2025-12-29 02:29

import services.ticket.models.complaint_ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintaction',
            options={'default_permissions': (), 'permissions': [('can_action_complaint_ticket', 'Can action complaint ticket')], 'verbose_name': 'ticket complaint action', 'verbose_name_plural': 'ticket complaint actions'},
        ),
        migrations.AlterModelOptions(
            name='complaintticket',
            options={'default_permissions': (), 'permissions': [('can_add_complaint_ticket', 'Can add complaint ticket'), ('can_view_complaint_ticket', 'Can view complaint ticket'), ('can_change_complaint_ticket', 'Can change complaint ticket'), ('can_delete_complaint_ticket', 'Can delete complaint ticket')], 'verbose_name': 'ticket complaint', 'verbose_name_plural': 'ticket complaints'},
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='identifier',
            field=models.CharField(blank=True, default=services.ticket.models.complaint_ticket.generate_order_id, max_length=20, null=True),
        ),
    ]
