# Generated by Django 5.2.6 on 2026-01-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_complaintaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintticket',
            name='order_type',
            field=models.CharField(choices=[('konveksi', 'Konveksi'), ('marketplace', 'Marketplace')], default='konveksi', max_length=20),
            preserve_default=False,
        ),
    ]
