# Generated by Django 5.2.6 on 2025-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identity',
            field=models.CharField(blank=True, help_text='Auto-generated customer code, e.g., CUSTK-0001', max_length=15, null=True, unique=True),
        ),
    ]
