# Generated by Django 5.2.6 on 2026-02-14 16:03

import core.common.generators
import services.account.models.module
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_role_subid_user_subid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('code', models.CharField(default=services.account.models.module.generate_random_code, max_length=256, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
    ]
