# Generated by Django 5.2.6 on 2026-02-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='module',
            field=models.ManyToManyField(blank=True, related_name='roles', to='account.module', verbose_name='modules'),
        ),
    ]
