# Generated by Django 5.2.6 on 2026-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_role_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='module',
            field=models.ManyToManyField(blank=True, to='account.module', verbose_name='modules'),
        ),
    ]
