# Generated by Django 5.2.6 on 2026-07-02 04:44

import core.common.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposit', '0010_deposit_pic'),
        ('forecast', '0012_alter_forecast_forecast_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='deposit.deposit')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='forecast.forecast')),
            ],
            options={
                'permissions': [('can_add_queue_entry', 'Can add queue entry'), ('can_view_queue_entry', 'Can view queue entry'), ('can_change_queue_entry', 'Can change queue entry'), ('can_delete_queue_entry', 'Can delete queue entry')],
                'default_permissions': (),
            },
        ),
    ]
