# Generated by Django 5.2.6 on 2026-07-02 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_alter_order_identifier'),
        ('queue_entry', '0002_queueentry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='order.orderitem'),
        ),
    ]
