# Generated by Django 5.2.6 on 2026-07-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_deposit_pic'),
        ('queue_entry', '0003_queueentry_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='deposit.deposit'),
        ),
    ]
