# Generated by Django 5.2.6 on 2025-10-07 13:46

import services.product.rest.product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.product.rest.product.utils.product_image_upload_path, verbose_name='image'),
        ),
    ]
