# Generated by Django 5.2.6 on 2025-10-08 11:28

import core.common.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'fabric type',
                'verbose_name_plural': 'fabric types',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('code', models.CharField(choices=[('A', 'Khusus Atasan'), ('B', 'Khusus Stelan & Atasan Bolak Balik'), ('C', 'Khusus Stelan Bolak Balik')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'product variant type',
                'verbose_name_plural': 'product variant types',
            },
        ),
    ]
