# Generated by Django 5.2.6 on 2025-10-08 11:30

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_fabrictype_productvarianttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('min_qty', models.PositiveIntegerField()),
                ('max_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='product.product')),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='product.productvarianttype')),
            ],
            options={
                'verbose_name': 'fabric type',
                'verbose_name_plural': 'fabric types',
                'ordering': ['min_qty'],
                'unique_together': {('product', 'variant_type', 'min_qty', 'max_qty')},
            },
        ),
    ]
