# Generated by Django 5.2.6 on 2025-10-08 11:37

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productpricetier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.fabrictype')),
                ('product_price_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_adjustments', to='product.productpricetier')),
            ],
            options={
                'verbose_name': 'product price adjustmen',
                'verbose_name_plural': 'product price adjustmens',
            },
        ),
    ]
