# Generated by Django 5.2.6 on 2025-10-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productpriceadjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpricetier',
            options={'ordering': ['min_qty'], 'verbose_name': 'price tier', 'verbose_name_plural': 'price tiers'},
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='variant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_tiers', to='product.productvarianttype'),
        ),
    ]
