# Generated by Django 5.2.6 on 2025-10-14 13:42

import core.common.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productpricetier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=core.common.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_prices', to='product.fabrictype')),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_prices', to='product.productvarianttype')),
            ],
            options={
                'verbose_name': 'fabric price',
                'verbose_name_plural': 'fabric prices',
                'unique_together': {('fabric_type', 'variant_type')},
            },
        ),
    ]
