# Generated by Django 5.2.6 on 2025-10-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_fabricprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPriceAdjustment',
        ),
    ]
