# Generated by Django 5.2.6 on 2025-10-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_productpriceadjustment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
