# Generated by Django 5.2.6 on 2025-10-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarianttype',
            name='code',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
