# Generated by Django 5.2.6 on 2025-10-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productvarianttype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricprice',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'fabric price', 'verbose_name_plural': 'fabric prices'},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'fabric type', 'verbose_name_plural': 'fabric types'},
        ),
        migrations.AlterModelOptions(
            name='productpricetier',
            options={'default_permissions': (), 'ordering': ['min_qty'], 'permissions': (), 'verbose_name': 'price tier', 'verbose_name_plural': 'price tiers'},
        ),
        migrations.AlterModelOptions(
            name='productvarianttype',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'product variant type', 'verbose_name_plural': 'product variant types'},
        ),
    ]
