# Generated by Django 5.2.6 on 2025-10-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_fabricprice_options_alter_fabrictype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarianttype',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
