# Generated by Django 5.2.6 on 2025-11-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productvarianttype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarianttype',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
