# Generated by Django 5.2.6 on 2025-12-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_alter_forecast_order_item'),
        ('product', '0015_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='forecast',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='forecast.forecast'),
            preserve_default=False,
        ),
    ]
