# Generated by Django 5.2.6 on 2026-01-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productstock_forecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'default_permissions': (), 'permissions': [('can_add_fabric_type', 'Can add fabric type'), ('can_view_fabric_type', 'Can view fabric type'), ('can_change_fabric_type', 'Can change fabric type'), ('can_delete_fabric_type', 'Can delete fabric type')], 'verbose_name': 'fabric type', 'verbose_name_plural': 'fabric types'},
        ),
    ]
