# Generated by Django 5.2.6 on 2026-02-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_fabrictype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvarianttype',
            options={'default_permissions': (), 'permissions': (('add_productvarianttype', 'Can add product variant type'), ('change_productvarianttype', 'Can change product variant type'), ('delete_productvarianttype', 'Can delete product variant type'), ('view_productvarianttype', 'Can view product variant type')), 'verbose_name': 'product variant type', 'verbose_name_plural': 'product variant types'},
        ),
    ]
